{% set name = "faststream" %}
{% set version = "0.5.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/faststream-{{ version }}.tar.gz
  sha256: 3773cb5d14612c245d0dad774956f22958e5d70b967bd94dfc17b38332fbbc2d

build:
  entry_points:
    - faststream = faststream.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - anyio >=3.7.1,<5
    - fast-depends >=2.4.0b0,<2.5.0
    - typer >=0.9,!=0.12,<1
    - typing-extensions >=4.8.0

test:
  imports:
    - faststream
  commands:
    - pip check
    - faststream --help
  requires:
    - pip

about:
  home: https://github.com/airtai/FastStream
  summary: 'FastStream: the simplest way to work with a messaging queues'
  dev_url: https://github.com/airtai/FastStream
  doc_url: https://faststream.airt.ai/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
