{% set name = "faststream" %}
{% set version = "0.5.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/faststream-{{ version }}.tar.gz
  sha256: cc6884afd8713fa5a99a8cd06e9d249c6c2b6f8ecfa9e3cf4564600d3eeb7131

build:
  entry_points:
    - faststream = faststream.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.8.0
    - anyio >=3.7.1,<5
    - fast-depends >=2.4.0b0,<3.0.0
    - typer >=0.9,!=0.12,<1
    - watchfiles >=0.15.0,<0.25.0

test:
  imports:
    - faststream
  commands:
    - pip check
    - faststream --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/airtai/FastStream
  summary: 'FastStream: the simplest way to work with a messaging queues'
  dev_url: https://github.com/airtai/FastStream
  doc_url: https://faststream.airt.ai/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
