schema_version: 1

context:
  name: faststream
  version: "0.6.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/faststream-${{ version }}.tar.gz
  sha256: de87502e22db0372131165221728c6993b29d42ba29aaaa0a27d1249803f2ddd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - faststream = faststream.__main__:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build
    - pip
  run:
    - python >=${{ python_min }}
    - typing_extensions >=4.12.0
    - anyio >=4.0,<5
    - fast-depends >=3.0.0
    - typer >=0.9,!=0.12,<=0.20.1
    - watchfiles >=0.15.0,<1.2.0

tests:
  - python:
      imports:
        - faststream
      python_version: ${{ python_min }}.*
  - script:
      - faststream --help

about:
  summary: 'FastStream: the simplest way to work with a messaging queues'
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ag2ai/faststream
  repository: https://github.com/ag2ai/faststream
  documentation: https://faststream.airt.ai/latest/

extra:
  recipe-maintainers:
    - carlodri
